# env_vars.sh

## TEMPORAL 
export nc_noaa="/data/projects/REMOSAT/tamnnm/wrf_data/netcdf/noaa/noaa_hourly_1877_1972"

## PERMANENT
export wrf="/work/users/tamnnm/WRF"
export wrf_run="$wrf/run_dir"
<<<<<<< HEAD
export wrf_test="/work/users/tamnnm/WRF/WRF/test"
export wps="/work/users/tamnnm/WRF/WPS_All"
export work="/work/users/tamnnm"
export code="$work/code"
export pkg="/work/users/tamnnm/code/pkg"
export vnm_sp="/work/users/tamnnm/geo_info/vnm/full_shp/vnm_admbnda_adm0_gov_20200103.shp"
export myhome="/home/users/tamnnm"
export download="/work/users/tamnnm/download_code"
export data="/data/projects/REMOSAT/tamnnm"
export twcr="work/users/tamnnm/Data/pap25_QA_1945/cal/twcr"
export datathay="/work/users/thanhnd/dat_OBS_grid"
export wrfdata="$data/wrf_data"
export trash="/work/users/tamnnm/trashbin"
export current_code="$code/1.main_code/4.trop_cyc/tcdetection_code/python_ver"
export current_data="$data/iwtrc/ASEAN"
export test="/work/users/tamnnm/code/sup/test"
=======
export wrf_test="$wrf/WRF/test"
export wps="$wrf/WPS_All"
export work="/work/users/tamnnm"
export code="$work/code"
export pkg="$code/03.pkg"
export sup="$code/02.sup"
export mcode="$code/01.main_code"
export img="$sup/image"
export vnm_sp="$work/geo_info/vnm/full_shp/vnm_admbnda_adm0_gov_20200103.shp"
export download="$work/download_code"
export data="/data/projects/REMOSAT/tamnnm"
export twcr="work/users/tamnnm/Data/pap25_QA_1945/cal/twcr"
export datathay="/work/users/thanhnd/dat_OBS_grid"
export wrf_data="$data/wrf_data"
export trash="$work/trashbin"
export current_code="$code/1.main_code/4.trop_cyc/tcdetection_code/python_ver"
export current_data="$data/iwtrc/ASEAN"
export test="$sup/test"
# export myprod="$data"
>>>>>>> c80f4457 (First commit)
export myprod="/prod/projects/gemmes/tamnnm"
export prod_wrf="$myprod/wrf"
